name: publish to github pages

on:
  push:
    branches: [ main ]

# Cancel already running jobs
concurrency:
  group: publish_to_pages_${{ github.head_ref }}
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Linux Publish
            runner: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.setup_pages.outputs.base_url }}
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Setup Pages
      uses: actions/configure-pages@v4
      id: setup_pages
    - name: Setup web_root
      run: |
        # Build binary for analysis
        cargo build --release
        # cargo run-wasm --release --build-only

        mkdir web_root
        cp target/release/executable-visualizer web_root/example

    - name: Upload pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'web_root'
    - name: Deploy pages
      uses: actions/deploy-pages@v4
